### ISSUE TITLE
Error at startup

### ISSUE THREAD

**Issue by Davikar** [huchenlei/sd-webui-openpose-editor#2]
Getting this error message at startup:
```

23:50:36-974230 ERROR    executing callback: C:\AI\automatic\extensions\sd-webui-openpose-editor\scripts\openpose_editor.py app_started_callback: RuntimeError
╭──────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────────────────────────────────────────╮
│ C:\AI\automatic\modules\script_callbacks.py:134 in app_started_callback                                                                                                                    │
│                                                                                                                                                                                            │
│   133 │   │   │   t0 = time.time()                                                                                                                                                         │
│ ❱ 134 │   │   │   c.callback(demo, app)                                                                                                                                                    │
│   135 │   │   │   timer(t0, c.script, 'app_started')                                                                                                                                       │
│                                                                                                                                                                                            │
│ C:\AI\automatic\extensions\sd-webui-openpose-editor\scripts\openpose_editor.py:99 in mount_openpose_api                                                                                    │
│                                                                                                                                                                                            │
│    98 │   │   "/openpose_editor",                                                                                                                                                          │
│ ❱  99 │   │   StaticFiles(directory=DIST_DIR, html=True),                                                                                                                                  │
│   100 │   │   name="openpose_editor",                                                                                                                                                      │
│                                                                                                                                                                                            │
│ C:\AI\automatic\venv\lib\site-packages\starlette\staticfiles.py:57 in __init__                                                                                                             │
│                                                                                                                                                                                            │
│    56 │   │   if check_dir and directory is not None and not os.path.isdir(directory):                                                                                                     │
│ ❱  57 │   │   │   raise RuntimeError(f"Directory '{directory}' does not exist")                                                                                                            │
│    58                                                                                                                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Directory 'extensions/sd-webui-openpose-editor/dist' does not exist

```
Tested on Windows 11, SD Next (Version: 9726b4d2), ControlNet v1.1.217, Python 3.10.10

Build: c604d36

**Comment by huchenlei** [comment]
Fixed in [9768dab](https://github.com/huchenlei/sd-webui-openpose-editor/commit/9768dab416d7e87820f5527aed54432e97a4422c). Was using wrong unzip dir.

**Comment by XuDong-Zhang** [comment]
> Fixed in [9768dab](https://github.com/huchenlei/sd-webui-openpose-editor/commit/9768dab416d7e87820f5527aed54432e97a4422c). Was using wrong unzip dir.已修复于 9768dab。使用了错误的解压缩目录。



> Fixed in [9768dab](https://github.com/huchenlei/sd-webui-openpose-editor/commit/9768dab416d7e87820f5527aed54432e97a4422c). Was using wrong unzip dir.

the newest version of master, the same wrong is still existing~~~

**Comment by huchenlei** [comment]
If you have hard time downloading dist automatically. You can manually download dist from release page.
